### ISSUE TITLE
CI issues in Gitlab project

### ISSUE THREAD

**Issue by mullinix** [scruffaluff/scaffold-python#3]
**Background**
- When using `scaffold-python` to generate a GitLab-based project last week the CI failed
- Example pipeline output:
```
$ poetry run bandit -ilr src/
Creating virtualenv <project>-py3.10 in /root/.cache/pypoetry/virtualenvs
Command not found: bandit
Cleaning up project directory and file based variables
ERROR: Job failed: exit code 1
```
- In the `poetry.lock` _and_ in `pyproject.toml` the package `bandit` is defined for development, but for some reason it isn't picked up when creating the venv
- I noticed that in previous versions the `.gitlab-ci.yml` was configured in the `before_script` block to run a `poetry install`:
```
default:
  before_script:
    - python -m pip install --upgrade pip poetry setuptools wheel
    - poetry config virtualenvs.in-project true
    - poetry install -v
```
- Adding the `poetry config` and `poetry install` lines fixed all issues.

**TODO**
- Were these changes added on purpose for streamlining or efficiency, or were these not supposed to be removed?

**Comment by scruffaluff** [comment]
That definitely is a bug. The lines were accidentally removed. Will fix in an upcoming PR.

**Comment by scruffaluff** [comment]
Fix has been merged into the main branch and has been tested in GitLab CI. Issue should be resolved now. Let me know if the issue persists for you.

**Comment by mullinix** [comment]
ty! I'll let you know if i run into any problems.
